name: close-stale-issues
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    uses: basel5001/githubinfra/.github/workflows/stale-management.yml@main
    with:
      days-before-stale: 45
      days-before-close: 5
      exempt-issue-labels: "future"
      exempt-pr-labels: "awaiting-approval, work-in-progress"